### ISSUE TITLE
Save optical flow as PNG

### ISSUE THREAD

**Issue by Ahleroy** [ProfFan/UnrealOpticalFlowDemo#1]
Hello,

Is there a way to save the optical flow as PNG in real-time ?

Many thanks

**Comment by ProfFan** [comment]
There are a few options:
1. You can try [directly](https://answers.unrealengine.com/questions/384499/texturerendertarget2d-saved-to-png-is-much-darker.html) use C++ for this task, though I do not recommend as this would be too much performance impact
2. You can use UE4's socket function and create a local socket to another companion application (Python or something) and send the data to it, and compress to PNG there. This would be a lot faster, and you can also send metadata like timestamps. I personally recommend this method.

Also note that PNG is probably not what you want, as it is always better to save as RAW and compress to PNG later if you have a big, fast SSD :)

Best,

Fan

**Comment by Ahleroy** [comment]
Thank you very much for your answer. 
I will try to implement the two options and see which one is the best for my application.

**Comment by ProfFan** [comment]
closing for now. Please open an new issue if you have more question.
