### ISSUE TITLE
HELP on saving data

### ISSUE THREAD

**Issue by HaiyiMei** [ProfFan/UnrealOpticalFlowDemo#5]
Great work! This repo helps me a lot!
I'm new to UE4 and facing some problems generating optical flow from a fixed camera view. I want to ask if there is a way to save RGB image and optical flow image as files `simultaneously` from `the same view of a camera actor`? Appreciated!

**Comment by ProfFan** [comment]
For this functionality please refer to AirSim or the Pavilion source code. Basically you create two camera objects, render them to a texture, and save that texture. I think they trigger at the same time if you do it in the main game loop.

**Comment by HaiyiMei** [comment]
> For this functionality please refer to AirSim or the Pavilion source code. Basically you create two camera objects, render them to a texture, and save that texture. I think they trigger at the same time if you do it in the main game loop.

Thx for your reply. I've achieved this function through this [repo](https://github.com/TimmHess/UnrealImageCapture).
